# Generated by Django 2.2.16 on 2020-09-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routines",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("routine", models.BigIntegerField()),
                ("player", models.BigIntegerField()),
                ("description", models.BigIntegerField()),
                (
                    "routineID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines_routineID",
                        to="home.CustomText",
                    ),
                ),
            ],
        ),
    ]
