# Generated by Django 2.2.16 on 2020-09-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_routines'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='routinesID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='userID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='userroutineID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_userroutineID', to='home.HomePage'),
        ),
    ]
