# Generated by Django 2.2.16 on 2020-09-16 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20200916_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='homepage_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
